### ISSUE TITLE
0.4.0 is not published on pypi

### ISSUE THREAD

**Issue by gaelgatelement** [Blueshoe/pytest-kubernetes#29]
# Description

0.4.0 was released 3 weeks ago, but [pypi still has only 0.3.1](https://pypi.org/project/pytest-kubernetes/#history)

**Comment by liquidiert** [comment]
Hey @gaelgatelement sorry for the inconveniences. We are publishing 0.4.0 today and adding the new publishing pipeline of pypi, ensuring new releases will be published in the future.

**Comment by liquidiert** [comment]
@gaelgatelement I release version 0.5.0 (skipping 0.4.0) with support for namespaces in the logs() function
